# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: thedeveloperguy
ko_fi: thedeveloperguy
custom: ['https://paypal.me/Durucz?country.x=HU&locale.x=hu_HU']
